# exception is an error
try:
    a = 50
    b = 0
    print(a / b)
except :
    print("OOPS!")


try:
    print(name)

except:
    print("Error ")

finally:
    print("Thank  u")